create table if not exists public.data_snapshots (
  id bigint generated by default as identity primary key,
  source_key text not null,
  source_name text not null,
  category text not null,
  region_code text not null default 'all',
  prefecture_code text not null default 'all',
  snapshot_date date not null,
  generated_at timestamptz not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_key, category, region_code, prefecture_code, snapshot_date)
);

create table if not exists public.demand_forecasts (
  id bigint generated by default as identity primary key,
  category text not null,
  region_code text not null,
  forecast_date date not null,
  demand_score numeric not null,
  demand_label text not null,
  confidence numeric not null,
  drivers jsonb not null,
  payload jsonb not null,
  generated_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category, region_code, forecast_date)
);

create index if not exists data_snapshots_date_idx
  on public.data_snapshots (snapshot_date desc, source_key, category);

create index if not exists data_snapshots_payload_gin_idx
  on public.data_snapshots using gin (payload);

create index if not exists demand_forecasts_date_idx
  on public.demand_forecasts (forecast_date desc, region_code, category);

alter table public.data_snapshots enable row level security;
alter table public.demand_forecasts enable row level security;

grant select on public.data_snapshots to anon, authenticated;
grant select on public.demand_forecasts to anon, authenticated;
grant all on public.data_snapshots to service_role;
grant all on public.demand_forecasts to service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'data_snapshots'
      and policyname = 'Public read data snapshots'
  ) then
    create policy "Public read data snapshots"
      on public.data_snapshots
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'demand_forecasts'
      and policyname = 'Public read demand forecasts'
  ) then
    create policy "Public read demand forecasts"
      on public.demand_forecasts
      for select
      using (true);
  end if;
end $$;
